cinder-api:
  image: michaelhenkecinder-api:liberty
  net: host
  env_file: /etc/docker/contrail/common.env
cinder-scheduler:
  image: michaelhenkecinder-scheduler:liberty
  net: host
  env_file: /etc/docker/contrail/common.env
