version: '2'
networks:
  undercloud:
    external: true
services:
  keystone:
    extends:
      file: /root/docker-opencontrail/compose/common/1.0/docker-compose.yml
      service: mariadb
      links:
      - mariadb 
    image: michaelhenkel/keystone:liberty
    #network_mode: host
    env_file: /etc/docker/contrail/common.env
    networks:
    - undercloud
