nova-api:
  cap_add:
    - NET_ADMIN
  image: michaelhenkel/nova-api:liberty
  net: host
  env_file: /etc/docker/contrail/common.env
nova-cert:
  image: michaelhenkel/nova-cert:liberty
  net: host
  env_file: /etc/docker/contrail/common.env
nova-conductor:
  image: michaelhenkel/nova-conductor:liberty
  net: host
  env_file: /etc/docker/contrail/common.env
nova-consoleauth:
  image: michaelhenkel/nova-consoleauth:liberty
  net: host
  env_file: /etc/docker/contrail/common.env
nova-novncproxy:
  image: michaelhenkel/nova-novncproxy:liberty
  net: host
  env_file: /etc/docker/contrail/common.env
nova-scheduler:
  image: michaelhenkel/nova-scheduler:liberty
  net: host
  env_file: /etc/docker/contrail/common.env
