cassandra:
  image: michaelhenkecassandra:1.0
  net: host
  env_file: /etc/docker/contrail/common.env
  volumes:
   -dockervolumecassandravalicassandrdatavalicassandrdata
zookeeper:
  image: michaelhenkezookeeper:1.0
  net: host
  env_file: /etc/docker/contrail/common.env
  volumes:
    -dockervolumezookeepervalizookeepervalizookeeper
  environment:
    - ADVERTISED_HOST=192.168.0.1
    - ADVERTISED_PORT=9092
