version: '2'
networks:
 undercloud:
   external: true
services:
  consul:
    image: progrium/consul
    #env_file: common.env
    #network_mode: "host"
    networks: 
      - undercloud
    ports:
      - 8500:8500
      - 8600:53/udp
    command: -server -bootstrap -log-level debug -advertise 10.87.64.34
#gliderlabs/registrator
  registrator:
    image: gliderlabs/registrator
    networks:
      - undercloud
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: consul://10.87.64.34:8500
