version: '2'
services:
  control-control:
    image: michaelhenkel/control-control:3.0-23b51ef
    network_mode: host
    env_file: /etc/docker/contrail/common.env
  control-dns:
    depends_on:
      - control-named
    pid: host
    volumes_from:
      - control-named
    cap_add:
      - ALL
    image: michaelhenkel/control-dns:3.0-23b51ef
    network_mode: host
    env_file: /etc/docker/contrail/common.env
  control-named:
    volumes:
      - /etc/contrail
    pid: host
    privileged: true
    image: michaelhenkel/control-named:3.0-23b51ef
    network_mode: host
    env_file: /etc/docker/contrail/common.env
