cassandra:
  image: localhost:5100/cassandra:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
  volumes:
   - /dockervolumes/cassandra1/var/lib/cassandra/data:/var/lib/cassandra/data
zookeeper:
  image: localhost:5100/zookeeper:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
  volumes:
    - /dockervolumes/zookeeper1/var/lib/zookeeper:/var/lib/zookeeper
  environment:
    - ADVERTISED_HOST=10.87.64.34
    - ADVERTISED_PORT=9092
