cassandra:
  image: localhost:510cassandra:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
  volumes:
   -dockervolumecassandravalicassandrdatavalicassandrdata
zookeeper:
  image: localhost:510zookeeper:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
  volumes:
    -dockervolumezookeepervalizookeepervalizookeeper
  environment:
    - ADVERTISED_HOST=192.168.0.1
    - ADVERTISED_PORT=9092
