version: '2'
networks:
  undercloud:
    external: true
  ext:
    external: true
services:
  control_2:
    image: michaelhenkel/network:1.0
    ports:
      - 53:53
      - 53:53/udp
      - 179:179
      - 5269:5269
      - 8083:8083
      - 8092:8092
      - 8093:8093
      - 8094:8094
    networks:
      - ext
      - undercloud
  control-control_2:
    environment:
      - IFMAP_USER=ctrl2
      - IFMAP_PASSWORD=ctrl2
    image: michaelhenkel/control-control:3.0.1-e24cc66
    network_mode: "service:control_2"
    env_file: common.env
    depends_on:
      - control_2
  control-named_2:
    environment:
      - IFMAP_USER=ctrl2
      - IFMAP_PASSWORD=ctrl2
    pid: host
    privileged: true
    image: michaelhenkel/control-named:3.0.1-e24cc66
    network_mode: "service:control_2"
    env_file: common.env
    depends_on:
      - control_2
