version: '2'
networks:
  default:
    external:
      name: undercloud
services:
  redis:
    image: michaelhenkel/redis:1.0
    env_file: common.env
  rabbitmq:
    image: rabbitmq:latest
    env_file: common.env
    environment:
      - RABBITMQ_NODE_IP_ADDRESS=0.0.0.0
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 25672:25672
  memcached:
    image: michaelhenkel/memcached:1.0
    env_file: common.env
    ports:
      - 12111:12111
  mariadb:
    volumes:
      - /var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    image: michaelhenkel/mariadb:1.0
    env_file: common.env
    ports:
      - 3306:3306
  keystone:
    image: michaelhenkel/keystone:liberty
    env_file: common.env
    ports:
      - 5000:5000
      - 35357:35357
    depends_on:
      - mariadb
  neutron-server:
    image: michaelhenkel/neutron-server:liberty
    env_file: common.env
    ports:
      - 9696:9696
    depends_on:
      - mariadb
  cassandra:
    image: michaelhenkel/cassandra:1.0
    ports:
    - 9160:9160
    - 7000:7000
    - 39470:39470
    - 9042:9042
    - 42590:42590
    - 7199:7199
    env_file: common.env
    environment:
    - CASSANDRA_LISTEN_ADDRESS=cassandra
    volumes:
     - /var/lib/cassandra/data
  zookeeper:
    image: michaelhenkel/zookeeper:1.0
    ports:
    - 2181:2181
    - 33366:33366
    env_file: common.env
    volumes:
      - /var/lib/zookeeper
  webui-server:
    image: michaelhenkel/webui-server:3.0.1-e24cc66
    ports:
    - 8143:8143
    - 8080:8080
    - 3000:3000
    - 3002:3002
    env_file: common.env
