version: '2'
networks:
  default:
    external:
      name: internal
services:
  glance:
    image: michaelhenkel/network:1.0
    ports:
      - 9191:9191
      - 9292:9292
  glance-api:
    image: michaelhenkel/glance-api:liberty
    env_file: common.env
    network_mode: "service:glance"
    depends_on:
      - glance
  glance-registry:
    image: michaelhenkel/glance-registry:liberty
    env_file: common.env
    network_mode: "service:glance"
    depends_on:
      - glance
