version: '2'
services:
  config-api:
    image: michaelhenkel/config-api:3.0-23b51ef
    network_mode: host
    env_file: /etc/docker/contrail/common.env
  config-device-manager:
    image: michaelhenkel/config-device-manager:3.0-23b51ef
    network_mode: host
    env_file: /etc/docker/contrail/common.env
  config-discovery:
    image: michaelhenkel/config-discovery:3.0-23b51ef
    network_mode: host
    env_file: /etc/docker/contrail/common.env
  config-schema:
    image: michaelhenkel/config-schema:3.0-23b51ef
    network_mode: host
    env_file: /etc/docker/contrail/common.env
  config-svc-monitor:
    image: michaelhenkel/config-svc-monitor:3.0-23b51ef
    network_mode: host
    env_file: /etc/docker/contrail/common.env
  ifmap:
    image: michaelhenkel/ifmap:3.0-23b51ef
    network_mode: host
    env_file: /etc/docker/contrail/common.env
#redis:
#  image: michaelhenkel/redis:1.0
#  network_mode: host
#  env_file: /etc/docker/contrail/common.env
