nova-api:
  cap_add:
    - NET_ADMIN
  image: localhost:510nova-api:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
nova-cert:
  image: localhost:510nova-cert:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
nova-conductor:
  image: localhost:510nova-conductor:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
nova-consoleauth:
  image: localhost:510nova-consoleauth:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
nova-novncproxy:
  image: localhost:510nova-novncproxy:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
nova-scheduler:
  image: localhost:510nova-scheduler:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
