config-api:
  image: localhost:510config-api:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
config-device-manager:
  image: localhost:510config-device-manager:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
config-discovery:
  image: localhost:510config-discovery:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
config-schema:
  image: localhost:510config-schema:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
config-svc-monitor:
  image: localhost:510config-svc-monitor:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
ifmap:
  image: localhost:510ifmap:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
redis:
  image: localhost:510redis:contrail-3.0-2668
  net: host
  env_file: /etc/docker/contrail/common.env
